services:
  - type: web
    name: medical-ai-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DATADOG_API_KEY
        sync: false
      - key: DATADOG_APP_KEY
        sync: false
      - key: DD_SITE
        value: us5.datadoghq.com
